- README.md
- package.json
> #72 update the private flag in package.json

- src/components/Pagination.tsx
- src/components/index.ts
- src/docs/pages/Pagination/Example.vue
- src/docs/pages/Pagination/index.ts
#6 
Implement the basic functionality of pagination, taking in itemsTotal, itemsPerPage, initialPage and event handler when update selected page
Yes, a simple Example.vue is added for illustration
> Implement Pagination

- NEW_COMPONENT/NEW_COMPONENT.md
To at least address some points raised by #79
> adds note about localization

- src/components/Combobox/Combobox.tsx
- src/components/Combobox/__tests__/Combobox.test.tsx
- src/docs/pages/Table/1-complex.vue
This is just a bugfix + more tests PR.
> fixes table example + related combobox bug + adds test

- .travis.yml
- src/components/Button/ButtonContainer.ts
Enables travis for linux. osx and windows outstanding due to issues.
> enables travis

- src/components/Tabs/Tabs.tsx
> add keyboard support

- src/components/Form/Controls/Input.tsx
- src/components/SearchInput/SearchInput.tsx
fixes issue #112 
Add support for `@change` event for <FdInput> component
I don't see `@input` event documented so I guess we don't document this. Right ?
> fix/ issue #112 add @ change support to input field

- package-lock.json
- package.json
Adding vue as a peer dependency will fix the error seen on bundlephobia: https://bundlephobia.com/result?p=fundamental-vue@0.0.12-beta
> chore: add vue as peer dependency

- package.json
#142 
Unifying the description across the fundamentals libraries
> chore: #142 update package.json description

- CONTRIBUTING.md
- NOTICE.txt
- README.md
- package-lock.json
> chore: #158 update README.md and CONTRIBUTING.md to reflect semantic versioning

- README.md
Adds references to the readme for ngx and react implementations of fundamentals.
> chore: add readme references to ngx and react versions

- ui/src/components/Icon/__tests__/Icon.test.ts
- ui/src/components/Icon/__tests__/__snapshots__/Icon.test.ts.snap
> fix : Created test cases for Icon

- docs/babel.config.js
- docs/src/api/_baseline.json
- docs/src/pages/Link/default.vue
- ui/jest.config.js
- ui/src/components/Link/Link.vue
- ui/src/components/Link/__tests__/Link.test.ts
Adds tests for the link component and adds a title prop to it.
> feat: Adds title-prop & tests to Link-component

- ui/src/components/Badge/__tests__/Badge.test.ts
- ui/src/components/Badge/__tests__/__snapshots__/Badge.test.ts.snap
> fix: Add tests for Badge Component

- ui/src/components/Label/__tests__/Label.test.ts
- ui/src/components/Label/__tests__/__snapshots__/Label.test.ts.snap
Tests for https://github.com/SAP/fundamental-vue/issues/197
> feat: add tests for Label component

- ui/src/components/Image/__tests__/Image.test.ts
- ui/src/components/Image/__tests__/__snapshots__/Image.test.ts.snap
Tests for https://github.com/SAP/fundamental-vue/issues/199
> feat: add tests for Image component

- ui/src/components/ActionBar/__tests__/ActionBar.test.ts
- ui/src/components/ActionBar/__tests__/__snapshots__/ActionBar.test.ts.snap
Tests for https://github.com/SAP/fundamental-vue/issues/190
> feat: add tests for ActionBar component

- ui/src/components/Counter/__tests__/Counter.test.ts
- ui/src/components/Counter/__tests__/__snapshots__/Counter.test.ts.snap
> fix : Add tests for Counter component

- ui/package.json
> fix: Adds fiori-fundamentals as a peer dependency in order to fix #165

- ui/src/components/Breadcrumb/__tests__/Breadcrumb.test.ts
- ui/src/components/Breadcrumb/__tests__/__snapshots__/Breadcrumb.test.ts.snap
- ui/src/components/BreadcrumbItem/__tests__/BreadcrumbItem.test.ts
- ui/src/components/BreadcrumbItem/__tests__/__snapshots__/BreadcrumbItem.test.ts.snap
Test for https://github.com/SAP/fundamental-vue/issues/191
> test: add tests for Breadcrumb and BreadcrumbItem components

- ui/src/components/Status/__tests__/Status.test.ts
- ui/src/components/Status/__tests__/__snapshots__/Status.test.ts.snap
> test cases added for status

- ui/src/components/Status/__tests__/Status.test.ts
Fix linting issue. Causing CI unable to build on master branch
> fix: linting test file for Status

- package.json
https://github.com/yarnpkg/yarn/issues/4984
> fix: change serve script for --cwd yarn issue

- ui/src/components/Token/__tests__/Token.test.ts
- ui/src/components/Token/__tests__/__snapshots__/Token.test.ts.snap
Tests for token https://github.com/SAP/fundamental-vue/issues/211
> test: add tests for Token component

- ui/src/components/ActionBar/__tests__/ActionBar.test.ts
- ui/src/components/Image/__tests__/Image.test.ts
- ui/src/components/Label/__tests__/Label.test.ts
- ui/src/components/ListGroup/__tests__/ListGroup.test.ts
- ui/src/components/ListGroup/__tests__/ListGroupItem.test.ts
- ui/src/components/ListGroup/__tests__/__snapshots__/ListGroup.test.ts.snap
- ui/src/components/ListGroup/__tests__/__snapshots__/ListGroupItem.test.ts.snap
> test: add tests for ListGroup and other linter issues

- package.json
- yarn.lock
fixes #237 
initing pre-commit block for lint.
> fix: add pre-commit for lint

- ui/src/components/InlineHelp/__tests__/InlineHelp.test.ts
- ui/src/components/InlineHelp/__tests__/__snapshots__/InlineHelp.test.ts.snap
> fix : Inline help test cases

- package.json
> fix: Fixes incorrect entry points (#175)

- ui/src/components/InlineHelp/__tests__/InlineHelp.test.ts
Hi, anyone can help to approve this? This is a fix for linting issue
> fix: linting issue at InlineHelp test

- ui/src/components/TileGrid/__tests__/TileGrid.test.ts
- ui/src/components/TileGrid/__tests__/__snapshots__/TileGrid.test.ts.snap
https://github.com/SAP/fundamental-vue/issues/208
Adds tests for TileGroup component
> test: adds tests for TileGroup component

- ui/src/components/Tile/ProductTile.vue
- ui/src/components/Tile/__tests__/ProductTile.test.ts
- ui/src/components/Tile/__tests__/Tile.test.ts
- ui/src/components/Tile/__tests__/__snapshots__/ProductTile.test.ts.snap
- ui/src/components/Tile/__tests__/__snapshots__/Tile.test.ts.snap
https://github.com/SAP/fundamental-vue/issues/207
Adds tests for Tile and ProductTile components
Fix type for ProductTile.isButton
> test: adds tests for Tile and ProductTile components

- ui/src/components/Form/Controls/__tests__/InputGroup.test.ts
- ui/src/components/Form/Controls/__tests__/__snapshots__/InputGroup.test.ts.snap
https://github.com/SAP/fundamental-vue/issues/198
Tests for InputGroup component
> test: adds tests for InputGroup component

- ui/src/components/TimePicker/TimePicker.vue
- ui/src/components/TimePicker/__tests__/Time.test.ts
- ui/src/components/TimePicker/__tests__/TimeAction.test.ts
- ui/src/components/TimePicker/__tests__/TimeInput.test.ts
- ui/src/components/TimePicker/__tests__/TimeItem.test.ts
- ui/src/components/TimePicker/__tests__/TimePicker.test.ts
- ui/src/components/TimePicker/__tests__/__snapshots__/Time.test.ts.snap
- ui/src/components/TimePicker/__tests__/__snapshots__/TimeAction.test.ts.snap
- ui/src/components/TimePicker/__tests__/__snapshots__/TimeInput.test.ts.snap
- ui/src/components/TimePicker/__tests__/__snapshots__/TimeItem.test.ts.snap
- ui/src/components/TimePicker/__tests__/__snapshots__/TimePicker.test.ts.snap
https://github.com/SAP/fundamental-vue/issues/210
https://github.com/SAP/fundamental-vue/issues/209
Tests for TimePicker, TimeItem, Time, TimeInput, TimeAction components\
Assign uid for Popover in TimePicker to prevent random snapshot mismatch
> test: adds tests for TimePicker, TimeItem, Time, TimeInput, TimeAction components

- ui/src/components/Spinner/__tests__/Spinner.test.ts
- ui/src/components/Spinner/__tests__/__snapshots__/Spinner.test.ts.snap
fix for issue #206  
adds unit tests for Spinner component 
not needed
> fix: Add unit tests for Spinner component

- ui/src/components/Panel/Panel.vue
- ui/src/components/Panel/__tests__/Panel.test.ts
- ui/src/components/Panel/__tests__/__snapshots__/Panel.test.ts.snap
https://github.com/SAP/fundamental-vue/issues/188
Adds slots for title and description
> fix(panel): adds slots for title and description

- ui/src/components/Button/Button.vue
- ui/src/components/Button/__tests__/Button.test.ts
- ui/src/components/TimePicker/Time/TimeInput.vue
- ui/src/components/TimePicker/__tests__/TimeInput.test.ts
> fix: Setting state to disabled on a button now properly disables the button

- docs/src/pages/Button/2-sizes.vue
- docs/src/pages/Button/4-groups.vue
- docs/src/pages/Button/5-groups-compact.vue
- ui/src/components/Button/Button.vue
- ui/src/components/Button/ButtonContainer.ts
- ui/src/components/Button/__tests__/Button.test.ts
- ui/src/components/ButtonGroup/ButtonGroup.vue
- ui/src/components/ButtonGroup/ButtonGroupButton.vue
- ui/src/components/ButtonGroup/__tests__/ButtonGroup.test.ts
- ui/src/components/TimePicker/__tests__/__snapshots__/Time.test.ts.snap
- ui/src/components/TimePicker/__tests__/__snapshots__/TimeAction.test.ts.snap
- ui/src/components/TimePicker/__tests__/__snapshots__/TimeItem.test.ts.snap
- ui/src/components/TimePicker/__tests__/__snapshots__/TimePicker.test.ts.snap
- ui/src/mixins/Compactable.ts
This fixes several small issues, adds tests and improves the documentation.
> fix: Fixes issue related to Button, ButtonGroup and ButtonGroupButton + compact mode

- package.json
- ui/src/components/Panel/__tests__/PanelGrid.test.ts
- ui/src/components/Panel/__tests__/__snapshots__/PanelGrid.test.ts.snap
issue #203
Adds test for PanelGrid component
> fix: Add tests for PanelGrid component

- docs/.eslintrc.js
- docs/src/components/ComponentExample.vue
- docs/src/components/ComponentReference/ComponentReference.vue
- docs/src/components/ComponentReference/PropsReference.vue
- docs/src/components/ExampleCollection.vue
- docs/src/components/StaticContent.vue
- docs/src/layouts/DefaultLayout.vue
- docs/src/layouts/FullscreenLayout.vue
- docs/src/layouts/default/ShellBar.vue
- docs/src/layouts/default/SideNav.vue
- docs/src/main.scss
- docs/src/shims-vue-types.d.ts
- docs/src/styles/_mixins.scss
- docs/src/styles/main.scss
- docs/src/styles/reset.scss
- ui/src/shims-vue-types.ts
- yarn.lock
Adds basic responsiveness to the documentation. Since we will move to a shared set of styles I did not put any additional effort into this.
> docs: Documentation is now (more) responsive

- README.md
- docs/public/auto-install-demo.html
- docs/public/auto-install-disabled-demo.html
- docs/src/DocsRouter/DocsRouter.ts
- docs/src/main.ts
- docs/src/static-pages/start.md
- ui/src/main.ts
> feat: Automatic Installation via script-tag

- docs/vue.config.js
- netlify.toml
- package.json
Add netlify command for PR previews
This pr will enable netlify previews on every pull request submitted. A bot will comment with a link to the preview and tell you what commit it was built on. If there is a failure, the bot will also comment with a link to the deploy logs for easier troubleshooting, found here: https://app.netlify.com/sites/fundamental-vue/deploys
We can customize the bot message if there's anything else you would find helpful :slightly_smiling_face: If you push updated commits, the site will rebuild and the comment will update itself with a new link. This takes around 5-8 minutes.
It is not currently set to block prs from being merged if there is a failure. We can enable that once we know everything is running smoothly.
The master branch will always be built at this …
> chore: add netlify command

- src/main.js
> feat: stub

- src/docs/pages/__tests__/examples.test.js
> fix: Prettier Warnings

- .eslintrc.js
- demo/pages/modal-default.vue
- src/components/Modal/Modal.vue
- src/components/Modal/ModalManager.js
- src/components/Modal/__tests__/ModalManager.test.js
- src/components/Modal/components/Overlay.vue
- src/components/Modal/lib/create-modal-portal.js
- src/components/Modal/lib/get-modals-container.js
- src/directives/modal.js
- src/docs/pages/Modal/0-default-modal.vue
- src/docs/pages/Modal/1-nested-modals.vue
- src/mixins/FocusTrap.js
- tests/e2e/plugins/index.js
- tests/e2e/specs/modal.js
for you ❤️ @albrechtjohannes  @trilodge
> feat: close modal on esc + nested modals

- src/components/Layout/ShellBar/ShellBarProductMenu.vue
- src/docs/pages/Shell Bar/3-products.vue
> fix: Product Menu Width

- src/components/$Support/on-click-outside.vue
- src/components/Popover/Popover.vue
Fixes a the click outside component. Did not work in FF <= v65
> fix: Click Outside Component

- src/components/VirtualizedList/VirtualizedList.vue
- src/docs/pages/Virtualized List/3-VirtualizedList-InitialLoad.vue
> fix: fixed initial load of virtualized list

- demo/main.scss
- package.json
- src/components/Dropdown/Dropdown.vue
- src/docs/main.scss
- src/docs/static-pages/start.md
- yarn.lock
> feat: switched to fundamental-styles

- src/components/VirtualizedList/VirtualizedList.vue
- src/docs/pages/Virtualized List/5-VirtualizedList-filter.vue
> fix: make virtualized list searchable

- package.json
> chore: removed execa dep

- src/components/VirtualizedList/VirtualizedList.vue
- src/docs/components/component-picker.vue
- src/docs/layouts/default/ShellBar.vue
> chore: fix expection in comp picker

- src/components/ActionBar/ActionBar.vue
- src/components/Alert/Alert.vue
- src/components/Badge/Badge.vue
- src/components/Breadcrumb/Breadcrumb.vue
- src/components/BreadcrumbItem/BreadcrumbItem.vue
- src/components/Button/Button.vue
- src/components/ButtonGroup/ButtonGroup.vue
- src/components/ButtonGroup/ButtonGroupButton.vue
- src/components/Calendar/Calendar.vue
- src/components/Combobox/Combobox.vue
- src/components/ContextMenu/ContextMenu.vue
- src/components/Counter/Counter.vue
- src/components/Counter/__tests__/Counter.test.js
> chore: improved api docs

- src/components/Form/FormLabel.vue
> fix: checkbox and label

- src/components/Layout/Container.vue
- src/docs/pages/Container/0-container-default.vue
- src/docs/pages/Container/1-container-fluid-default copy.vue
- src/docs/pages/Container/2-container-centered.vue
- src/docs/pages/Container/3-container-fluid-with-cols.vue
- src/docs/pages/Container/index.js
> feat: Container

- src/components/ComboboxBase/ComboboxBase.vue
- src/components/Popover/Popover.vue
- src/components/Popover/body-size-mode.js
- src/components/TimePicker/TimePicker.vue
- src/docs/components/CodeView.vue
- src/docs/components/ComponentExample.vue
- src/docs/components/Tip.vue
- src/docs/components/index.js
> fix/fixed popover z-index

- src/docs/layouts/default/ShellBar.vue
> chore: made logo in docs nicer

- src/components/Layout/ShellBar/ShellBarProductMenu.vue
> fix: fixed css issue (IE)

- .prettierrc.json
- src/docs/components/d-component-api-link.vue
- src/docs/components/d-example/d-example-footer.vue
> chore: fixed api link html

- src/components/Form/Controls/InputMixin.js
- src/components/Form/Controls/Radio.vue
- src/components/Form/Controls/Select.vue
- src/components/Form/Controls/Toggle.vue
- src/components/Form/Controls/__tests__/Checkbox.test.js
> fix: fixed radio button issue

- src/components/Form/FormItem.vue
- src/docs/content/examples/form/binding.vue
- src/docs/content/examples/form/mixing-model.vue
- src/docs/content/examples/form/select-model.vue
- src/docs/content/examples/form/states.vue
- src/docs/content/examples/identifier/sizes.vue
- yarn.lock
> fix: form examples

- src/components/tree/TreeItem.vue
- src/docs/content/examples/tree/organization.vue
use fundamental-styles scss for cross-browser support
Updating the css to use the fundamental-styles scss helpers + Removing external links from documentation
> updated documentation: removed external links

- src/components/Table/Components/TableRow.vue
- src/components/Table/table.vue
- src/components/Table/utils/normalized-headers.js
- src/docs/content/en_us/table.md
- src/docs/content/examples/table/default-no-cells.vue
Provide default cell content to avoid defining every cell template.
Yes, example and explanation added.
> initial commit: user still needs to put the fd-table-row in a template

- src/components/index.js
- src/components/objectTree/ObjectTree.vue
- src/components/objectTree/__tests__/ObjectTree.test.js
- src/components/objectTree/__tests__/__snapshots__/ObjectTree.test.js.snap
- src/components/objectTree/index.js
- src/components/objectTree/utils.js
- src/components/tree/__tests__/Tree.test.js
- src/docs/content/en_us/object-tree.md
- src/docs/content/en_us/tree.md
- src/docs/content/examples/object-tree/default.vue
- src/docs/content/examples/object-tree/json.vue
- src/docs/content/examples/object-tree/props.vue
updated documentation
added snapshots generated by test, removed empty data.js file from documentation
basic tree implementation
updated documentation
added snapshots generated by test, removed empty data.js file from documentation
lint fixes
initial component commit
updated documentation
styling the property values based on type (color + font style)
updated documentation
handling errors (not rendering anything but no console errors)
added tests
refactored tests and updated documentation
New component: object tree. It is built on top of the tree component and allows the user to render an object's properties in a tree structure
Yes, description and examples were added
> basic tree implementation

- src/components/SearchInput/SearchInput.vue
> fix: dynamic completions

- package.json
> requires a exact version of fundamental styles

- src/components/Modal/modal.scss
- src/docs/content/en_us/master-details.md
- src/docs/index.js
- yarn.lock
> fix: fixed docs + added new note

- package.json
- yarn.lock
> bumped standard-version

- src/components/combobox/combobox.vue
- src/components/input-group/__tests__/addon.test.js
- src/components/input-group/addon.vue
> added compact prop to addon and fixed combo box

- package.json
- src/components/list/index.js
- src/components/list/item-checkbox-label.vue
- src/components/list/item-checkbox.vue
- src/components/list/item.vue
- src/components/list/list.vue
- src/components/list/type.js
- src/docs/pages/list/dropdown.vue
- src/docs/pages/list/list.md
- src/docs/pages/list/multi-input.vue
- transition-guide.md
- yarn.lock
> feat: improved list + new styles version

- .storybook/main.js
- package.json
- stories/0-Welcome.stories.js
- stories/1-Button.stories.js
- stories/MyButton.js
- stories/Welcome.js
- yarn.lock
> adds basic storybook integration

- README.md
There is no `App.js` file, it ha to be `App.vue`
> Changed file name to App.vue

- .github/CONTRIBUTING.md
- .reuse/dep5
- LICENSE.txt
- NOTICE.txt
- README.md
> chore: migrate from CLA to DCO

- README.md
> chore: add REUSE badge

- .reuse/dep5
> chore: update dep5

- README.md
> chore: another try for reuse

- .reuse/dep5
- LICENSES/MIT.txt
> chore: add MIT for one file

- .reuse/dep5
> chore: format dep5

- .travis.yml
- README.md
- ci-scripts/publish.sh
- scripts/publish-release.sh
- src/docs/pages/list/list.md
There is migration from master to branch - it will require additional steps, to fully work. They are listed there:
https://github.com/SAP/fundamental-ngx/issues/3554
> chore: Migrate master to main branch

- package.json
There is incrementation of RC version in master from `47` to `51`, following npm versioning
> chore: Increment RC version

- ci-scripts/publish-rc.sh
- ci-scripts/publish.sh
- package.json
- yarn.lock
> chore: update bump version

- src/components/notifications/Notifications.vue
> bug fix: added opts.timeout
