SAP/fundamental-vue

src/components/Pagination/Pagination.tsx
src/components/Pagination/__tests__/Pagination.test.tsx

#6 
refer to https://sap.github.io/fundamental/components/pagination.html <More than three Pages>
introduce private prop 'numberOfNeighbour', it defines number of neighbour to show on the left and right from the selectedPage, e.g. selectedPage=27, then 26,27,28 should be shown in the pagination with nunmberOfNeighbour = 1

support ... when more than 3 pages and add more test

---

package.json
src/components/Counter.tsx

@deepshikha02 told me that `npm run serve:docs` does not work on windows. I have no windows machine but I think that this PR fixes the issues.
Also if this is merged you will be able to do `npm run serve` and `npm run serve:docs` will yield a warning.

 fixes npm run serve:docs and makes npm run serve the new default

---

src/components/Combobox/Combobox.tsx
src/components/Popover/Popover.tsx
src/docs/pages/Popover/2-custom-trigger.vue

2 clicks were needed to show the combobox
This also makes Popover more flexible by using scoped slots in order to let the developer customize the way the popover is triggered. Previously your trigger control had to emit click events which is not always the case (see combobox + click.native).

fixes combobox bug

---

src/components/Form/FormLabel.tsx

Hello 👋 
No issue for this.
```is-required``` css class has been removed from labels for required fields in Forms.
Here is an example from fiori-fundamentals
- added the ```aria-required``` to the label 
- added ```*``` to the label text
- removed the ```is-required``` class
no documentation change needed for this.
PS: I think prettier had a bit of fun formatting the file 😄 let me know if it's an issue and I can revert this
Cheers
Ramona 🐳

fix: add * to required label 

---

CHANGELOG.md
package.json
yarn.lock

The package `standard-version` apparently has a bug in v5.x that keep repeating the "Change Log" header on every change.  Downgrading to v4.x for now until that issue is resolved.

chore: Downgrade standard version to 4.x and cleanup change log file

---

.npmignore
.travis.yml
package.json

@jbadan, @greg-a-smith: If you check the released artefacts of `fundamental-vue@0.0.15-rc.2` you will notice that it only contains meta data information like a `package.json`-file. The actual artefacts (`FundamentalVue.umd.js`, …) are missing. There is no `dist`-folder. This is because `yarn build:ui` builds *Fundamental Vue* however the build result is located in `ui/dist` and not in `dist`. I have modified the `public-rc`-script accordingly.
I have tested it *locally* as best I could but I guess we have to merge this PR to see if it really works?
If it works I assume that the other script has to be adopted too. Right?
The project structure of Fundamental Vue is a little strange but this is how it works currently…

fix: Fixes CI Configuration

---

ui/src/components/ClickAwayContainer.ts
ui/src/components/Modal/Modal.vue
ui/src/components/Modal/__tests__/__snapshots__/Modal.test.ts.snap
ui/src/util/pluginify.ts

So this is how I would fix the modal.
It is ugly. :D By using an animation frame / setTimeout, we simply delay the registration of event handlers.
There are other ways to do it. One would be to use the same approach using for `FdPopover` which we already discussed within the context of the `FdPopper`-component. But this is a minimally invasive fix. I also think that the use case is different:
I think a trigger component and a simple popover usually share the same context. There is usually not a lot of reuse. However I might have a single "Save Modal" which I want to trigger from everywhere. At least this was the reason for doing it differently. But we will see. If you think this change is acceptable simply merge it into your branch.
If not: Let's talk. :D

fix: Fixes Modal using animation frame

---

docs/src/pages/Modal/Example.vue

Fixes #252
This adds the `stop` event modifier to the modal's example page "Show Modal" button in order to prevent that the button is immediately close again.

fix: Add stop event modifier on modal example page to avoid event propagation

---

ui/package.json
ui/src/components/Modal/Modal.vue
ui/src/components/Modal/__tests__/Modal.test.ts
ui/src/components/Modal/__tests__/__snapshots__/Modal.test.ts.snap
ui/src/mixins/FocusTrap.ts
ui/src/mixins/index.ts
ui/yarn.lock

**Associated Issue**
#236 
**Summary**
This PR improves the accessibility of the modal component by adding a focus trap that is bound to the modal when opening it. To achieve this, I added a dependency to https://github.com/davidtheclark/focus-trap and a mixin, which is currently used only in the modal. However, it could also be used in other components, for example the popover component.

feat: create focus trap mixin and add it to modal

---

docs/src/pages/Side Navigation/1-1-dynamic.vue
docs/src/pages/Side Navigation/1-2-dynamic-static.vue
docs/src/pages/Side Navigation/2-data-driven-complex-sync.vue
docs/src/pages/Side Navigation/3-data-driven-custom-render.vue
ui/src/components/InlineHelp/__tests__/InlineHelp.test.ts
ui/src/components/SideNav/Model/Item.ts
ui/src/components/SideNav/Model/Store.ts
ui/src/components/SideNav/Model/__tests__/Store.test.ts
ui/src/components/SideNav/SideNav.vue
ui/src/components/SideNav/SideNavGroup.vue
ui/src/components/SideNav/SideNavItem.vue
ui/src/components/SideNav/SideNavLink.vue
ui/src/components/SideNav/SideNavList.vue
ui/src/components/SideNav/SideNavSubLink.vue
ui/src/mixins/withTargetLocation.ts

I am breaking #178 up in multiple PRs to make things not so big.
This PR simply makes the id of side nav items options and cleans up parts of the code.
With this PR I am also starting a small SideNav overhaul. I would like to remove redundant code and add tests. This is a prerequisite for the overhaul.

feat: Side Navigation Item no longer requires an id to work

---

docs/package.json
docs/tsconfig.json
docs/yarn.lock
ui/package.json
ui/src/components/SideNav/SideNavLink.vue
ui/src/components/SideNav/SideNavSubLink.vue
ui/tsconfig.json
ui/yarn.lock
yarn.lock

This PR forces typescripts version to be in a certain fixed range. Usually simply using the `^` is preferred but this is not compatible with Vue at the moment. Using versions of typescript outside of the specified range causes Vue to complain while building for prod.
Furthermore, this PR continues the slow migration away from typescript.

fix: Fixes typescript version and related warnings

---

ci-scripts/publish.sh

n/a
It was found in the `fundamental` repo that the calls to GitHub API to build the release notes _could_ happen prior to the commits being pushed (or updated within GitHub).  To help ensure this works, I have moved the create release call below publish.
n/a

chore: Release notes

---

package.json
yarn.lock

n/a
Get new version of `github-assistant` that will include a "Documentation" section in the release notes.
n/a

chore: Include documentation section in release notes

---

package.json

`yarn deploy:docs` was missing some key steps - `yarn bootstrap` and `yarn build:ui`
The docs site should be working now. If you're seeing errors, try clearing the cache and hard reloading.

fix: docs site deploy, add missing build commands

---

README.md

Update the documentation link to the netlify documentation as the the one on github pages is not up to date.

chore: change documentation link in readme to the netlify documentation

---

README.md
ci-scripts/publish.sh
package.json

This should fix the documentation deployment issue, see https://github.com/SAP/fundamental-react/pull/402
Also updated the readme pointers to the docs site, as it will now be up to date.

fix: update docs deployment script

---

src/components/Modal/Modal.vue
src/components/Modal/modal.scss
src/docs/content/en_us/modal.md
src/docs/content/examples/modal/fullscreen-modal.vue

Some properties of the default modal styles were overridden to allow the dev to customize the size of the modal
Yes, a new example was added

modal dimensions can now be controlled and set to fullscreen if needed

---

src/components/Popover/Popover.vue
src/docs/content/en_us/popover.md
src/docs/content/examples/popover/default-styles.vue

The  popover was already forwarding a bodyStyles attribute to its internal implementation but was not explicitly mentioned. So, it was made into a prop  and sensible defaults were provided.
Yes new example was added.

bodyStyles is now a prop for Popover + updated documentation

---

src/components/Alert/Alert.vue
src/components/Alert/__tests__/Alert.test.js
src/components/Alert/__tests__/__snapshots__/Alert.test.js.snap
src/components/index.js
src/components/notifications/EventsBus.js
src/components/notifications/Notifications.vue
src/components/notifications/_notifications.animations.scss
src/components/notifications/_notifications.styles.scss
src/components/notifications/index.js
src/components/notifications/notifications.types.d.ts
src/docs/content/en_us/alert.md
src/docs/content/examples/alert/notifications-default.vue
src/docs/content/examples/alert/notifications-group.vue

updated alert component test snapshot
add notifications component and fdNotifications installation
updated documentation
Give consumers the ability to hide/show alerts in various positions on the screen.
Yes, new examples have been added in the alert component documentation

fix alert dismissible class

---

README.md

n/a
This PR updates the `Fundamental Vue in 5 Minutes or less` section in the getting started section. Instead of displaying two components it shows a single html document which can be used as it to get started. 
I'm adding that, because when trying it out with a colleague having a fully working example helped a lot to get up and running and reduces the uncertainty where exactly thing need to be placed (or not). 
Additionally the switch from `xml` to `html` for the markdown code section allows for better code highlighting (e.g. of javascript in the script tag)
n/a

update getting started with a fully working example

---

src/components/combobox/__tests__/combobox.test.js
src/components/combobox/combobox.vue
src/components/menu/menu-item.vue
src/docs/pages/combobox/combobox.md
src/docs/pages/combobox/labels.vue

Should address #302 
This PR adds the functionality of displaying the _label_ field instead of the _value_ field on Comboboxes
I have added a example to the docs

fix:  Display label instead of value on combobox when label is present

---

LICENSE.txt

In order to be able to identify the main license of all managed repositories centrally, the SAP Open Source Program Office (OSPO) asks all teams to have an identifiable license in their repositories. For some reason (probably formatting - we usually have these issues with licenses copied via the [REUSE tool](https://reuse.software)) the [license in this repository is not detected properly by GitHub](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository#detecting-a-license). This PR includes text from a [GitHub license template](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) that should facilitate the automated license detection.

chore: use GitHub license template
